version: "3"
services:
  lms_docker:
    build:
      context: .
      dockerfile: lms_docker.dockerfile
    container_name: lms-web-app
    volumes:
      - type: volume
        source: mydata
        target: /data
    restart: always
    ports:
      - "80:8081"
    networks:
      - lms_network

  lms:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - lms_network

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "YES"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD:

    volumes:
      - ../lms_db:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    networks:
      - lms_network
    ports:
      - 8080:8080

networks:
  lms_network:
    driver: bridge

volumes:
  mydata: