jwt:
  secret: javainuse
management:
  endpoints:
    web:
      expose: '*'
      exposure:
        include: '*'
server:
  ssl:
    key-store: classpath:springboot.jks
    key-store-password: password
    key-store-type: jks
    key-alias: springboot
    key-password: password
  port: 8443
  error:
    whitelabel:
      enabled: false
  # port: 8081
spring:
  cache:
    type: "none"
  datasource:
        password: root
        testWhileIdle: true
        url: jdbc:mysql://lms:3306/lms_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        validationQuery: SELECT 1
        driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  messages:
    basename: "i18n.message"
  servlet:
    multipart:
      max-file-size: 2500MB
      max-request-size: 2500MB
      enabled: true
      file-size-threshold: 2500MB
#AWS properties
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      use-default-aws-credentials-chain:  false
      accessKey: AKIAT5JBCLCQUNER5MNG
      secretKey: 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
          
application:
  bucket:
    image: prodlmsimage
    videoEnglish: prodlmstrainingvideo/english
    videoBengali: prodlmstrainingvideo/bengali
    certificate: prodlmscertificate

  logging:
    file:
      path: ./data/lms-web-app.log
      
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    suffix: .html
    template-loader-path: classpath:/templates
    